[package]
name = "hello_rust"
version = "0.1.0"
authors = ["laopo001 <353272497@qq.com>"]
edition = "2018"

[dependencies]

[features]
default = []
test = []

[package.metadata.commands]
wasm-build = "cargo build --target=wasm32-unknown-unknown --bin=wasm && node index.js"